Add npm installation check to deployment script

diff --git a/.github/workflows/cd_stage.yml b/.github/workflows/cd_stage.yml
--- a/.github/workflows/cd_stage.yml
+++ b/.github/workflows/cd_stage.yml
@@ -23,6 +23,8 @@ jobs:
             cd DevOps-bms
             echo "Pulling latest changes..."
             git pull origin main
+            echo "Checking npm install existence. if not then installing..."
+             which npm || (echo "npm not found, installing Node.js properly" && curl -fsSL https://deb.nodesource.com/setup_18.x | sudo -E bash - && sudo apt-get install -y nodejs)
             echo "Checking pnpm existence. if not then installing..."
             which pnpm || npm install -g pnpm
             echo "Installing dependencies..."
